services:
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb

  web:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT:-87}:80"
    networks:
      - app-network
    depends_on:
      - php

  mariadb:
    image: mariadb:10.11-rc
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: