services:
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb
    command: >
      sh -c "apk add --no-cache $PHPIZE_DEPS
      && apk add --no-cache libpng-dev libzip-dev zip unzip
      && docker-php-ext-install pdo pdo_mysql mysqli zip
      && php-fpm"
  web:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT:-87}:80"
    networks:
      - app-network
    depends_on:
      - php

  mariadb:
    image: mariadb:10.11-rc
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    networks:
      - app-network
    image: phpmyadmin
    restart: always
    ports:
        - '${APP_PORT_PHPMYADMIN:-82}:80'
    environment:
        - PMA_ARBITRARY=1
    depends_on:
        - mariadb
    links:
        - mariadb:db
networks:
  app-network:
    driver: bridge

volumes:
  db_data: